- hosts: all
  remote_user: root
  vars_files:
    - var.yaml

  tasks:
    - name: install flannel
      yum: name=flannel state=installed
    - name: config flanneld
      template: dest=/etc/sysconfig/flanneld src=flanneld.j2

## tree templates
[root@c03 ~]# tree
.
├── etcd.yaml
├── flannel.yaml
└── templates
    ├── etcd.conf.j2
    └── flanneld.j2
