version: '2'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "/data/db/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=liyang
      - MYSQL_DATABASE=owncloud

  owncloud:
    container_name: owncloud
    image: owncloud
    restart: always
    ports:
      - "8080:80"
    links: 
      - mysql:mysql
    volumes:
      - "/data/db/owncloud:/var/www/html/data"
